CREATE TABLE menu_item(
	[menuID] [int] IDENTITY(1,1) NOT NULL,
	[price]  MONEY NOT NULL,
 CONSTRAINT [PK_menu_item] PRIMARY KEY CLUSTERED 
(
	[menuID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE food(
	[foodID] [int] IDENTITY(1,1) NOT NULL,
	[name]  VARCHAR(255) NOT NULL,
	[category]  VARCHAR(255) NOT NULL,
	[menuID] [int] NOT NULL,	
 CONSTRAINT [PK_food] PRIMARY KEY CLUSTERED 
(
	[foodID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE drink(
	[drinkID] [int] IDENTITY(1,1) NOT NULL,
	[name]  VARCHAR(255) NOT NULL,
	[category]  VARCHAR(255) NOT NULL,
	[menuID] [int] NOT NULL,	
 CONSTRAINT [PK_drink] PRIMARY KEY CLUSTERED 
(
	[drinkID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
  
 CREATE TABLE ingredient(
	[ingredientID] [int] IDENTITY(1,1) NOT NULL,
	[amount]  VARCHAR(255) NOT NULL,
	[inventoryID]  [int] NOT NULL,
	[menuID] [int] NOT NULL,	
 CONSTRAINT [PK_ingredient] PRIMARY KEY CLUSTERED 
(
	[ingredientID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE employee(
	[employeeID] [int] IDENTITY(1,1) NOT NULL,
	[name]  VARCHAR(255) NOT NULL,
	[positionID]  [int] NOT NULL,	
 CONSTRAINT [PK_employee] PRIMARY KEY CLUSTERED 
(
	[employeeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
  
 CREATE TABLE position(
	[positionID] [int] IDENTITY(1,1) NOT NULL,
	[payRate]  MONEY NOT NULL,
 CONSTRAINT [PK_position] PRIMARY KEY CLUSTERED 
(
	[positionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
  
 CREATE TABLE cocktailRecipe(
	[drinkID] [int] IDENTITY(1,1) NOT NULL,
	[name]  VARCHAR(255) NOT NULL,
	[ingredient]  VARCHAR(255) NOT NULL,
	[amount] VARCHAR(255)NOT NULL,
	[menuID] [int] NOT NULL,	
 CONSTRAINT [PK_cocktailRecipe] PRIMARY KEY CLUSTERED 
(
	[drinkID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
 
 CREATE TABLE sale(
	[saleNumber] [int] IDENTITY(1,1) NOT NULL,
	[total]  VARCHAR(255) NOT NULL,		
 CONSTRAINT [PK_sale] PRIMARY KEY CLUSTERED 
(
	[saleNumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
 
CREATE TABLE customer(
	[customerID] [int] IDENTITY(1,1) NOT NULL,
	[name]  VARCHAR(255) NOT NULL,
	[creditCardNo]  VARCHAR(255) NOT NULL,
	[saleNumber] [int] NOT NULL,	
 CONSTRAINT [PK_customer] PRIMARY KEY CLUSTERED 
(
	[customerID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
 
 CREATE TABLE inventory(
	[inventoryID] [int] IDENTITY(1,1) NOT NULL,
	[name]  VARCHAR(255) NOT NULL,
	[stockQuantity]  VARCHAR(255) NOT NULL,
	[vendor]  VARCHAR(255) NOT NULL,	
 CONSTRAINT [PK_inventory] PRIMARY KEY CLUSTERED 
(
	[inventoryID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE seating(
	[tableID] [int] IDENTITY(1,1) NOT NULL,
	[employeeID] [int] NOT NULL,
	[name]  VARCHAR(255) NOT NULL,
	[visitDate]  VARCHAR(255) NOT NULL,
	[saleNumber] [int] NOT NULL,		
 CONSTRAINT [PK_seating] PRIMARY KEY CLUSTERED 
(
	[tableID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE customerOrder(
	[saleNumber] [int] IDENTITY(1,1) NOT NULL,
	[menuID] [int] NOT NULL,	
	[inventoryID] [int] NOT NULL,		
 CONSTRAINT [PK_customerOrder] PRIMARY KEY CLUSTERED 
(
	[saleNumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE employee ADD CONSTRAINT fk_employee
FOREIGN KEY (positionID) REFERENCES position (positionID);

ALTER TABLE customer ADD CONSTRAINT fk_customer
FOREIGN KEY (saleNumber) REFERENCES sale (saleNumber);

ALTER TABLE customerOrder ADD CONSTRAINT fk_customerOrder1
FOREIGN KEY (saleNumber) REFERENCES sale (saleNumber);

ALTER TABLE customerOrder ADD CONSTRAINT fk_customerOrder2
FOREIGN KEY (menuID) REFERENCES menu_item (menuID);

ALTER TABLE food ADD CONSTRAINT fk_food
FOREIGN KEY (menuID) REFERENCES menu_item (menuID);

ALTER TABLE drink ADD CONSTRAINT fk_drink
FOREIGN KEY (menuID) REFERENCES menu_item (menuID);

ALTER TABLE cocktailRecipe ADD CONSTRAINT fk_cocktailRecipe
FOREIGN KEY (menuID) REFERENCES menu_item (menuID);
